name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    if: github.event_name == 'push'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, linux-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.8.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

  deploy_wheels:
    needs: build_wheels
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - shell: bash
        working-directory: artifacts
        run: |
          for i in $( ls ); do
            mv $i dist
          done

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
