name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    if: github.event_name == 'push'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #[ubuntu-20.04, windows-2019, macOS-11]
        os: [windows-2019]
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install packages
        run:
          pip install wheel
          pip install numpy

      - name: Build wheels
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl

  deploy_wheels:
    needs: build_wheels
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
